## **2. Feature Engineering**

### Token Level Features
&emsp;a) Imports & Load Data

In [3]:
import pandas as pd
import numpy as np
from transformers import MarianTokenizer, MarianMTModel

In [4]:
df = pd.read_csv('data/fr_en_cleaned_train.csv')
df.head(5)

,user_id,sent_id,token,POS,Morpho-Syntactic_Features,Dependency-Relation,Dependancy-Head,time,p_recall,sentence
0,YjS/mQOx,8XTyQUAl01,Le,DET,Definite=Def|Gender=Masc|Number=Sing|fPOS=DET++,det,2,14.0,0,Le garçon
1,YjS/mQOx,8XTyQUAl01,garçon,NOUN,Gender=Masc|Number=Sing|fPOS=NOUN++,ROOT,0,14.0,0,Le garçon
2,YjS/mQOx,8XTyQUAl02,Je,PRON,Number=Sing|Person=1|PronType=Prs|fPOS=PRON++,nsubj,4,14.0,0,Je suis une femme
3,YjS/mQOx,8XTyQUAl02,suis,VERB,Mood=Ind|Number=Sing|Person=1|Tense=Pres|VerbF...,cop,4,14.0,0,Je suis une femme
4,YjS/mQOx,8XTyQUAl02,une,DET,Definite=Ind|Gender=Fem|Number=Sing|PronType=D...,det,4,14.0,0,Je suis une femme

In [5]:
tokens = df[['token', 'POS', 'Morpho-Syntactic_Features', 'sentence']]
tokens = tokens.drop_duplicates()
tokens.head(10)
print(tokens['token'].is_unique)

duplicate_rows = tokens[tokens.duplicated(subset=['token'], keep=False)]
print(duplicate_rows[duplicate_rows['token'] == 'suis'])
# i am preserving dup tokens because they have different POS and morpho-syntactic features which could be important for the model to learn. For example "suis" can be a verb (first person singular of "être") or a noun (plural of "sui" which is a type of plant). Removing duplicates would result in loss of information that could be relevant for the model to learn the correct associations between tokens, their POS tags, and their morpho-syntactic features.

False
       token   POS                          Morpho-Syntactic_Features  \
3       suis  VERB  Mood=Ind|Number=Sing|Person=1|Tense=Pres|VerbF...
9       suis  VERB  Mood=Ind|Number=Sing|Person=1|Tense=Pres|VerbF...
13      suis  VERB  Mood=Ind|Number=Sing|Person=1|Tense=Pres|VerbF...
16      suis  VERB  Mood=Ind|Number=Sing|Person=1|Tense=Pres|VerbF...
158     suis  VERB  Mood=Ind|Number=Sing|Person=1|Tense=Pres|VerbF...
...      ...   ...                                                ...
706231  suis  VERB  Mood=Ind|Number=Sing|Person=1|Tense=Pres|VerbF...
706249  suis  VERB  Mood=Ind|Number=Sing|Person=1|Tense=Pres|VerbF...
738926  suis  VERB  Mood=Ind|Number=Sing|Person=1|Tense=Pres|VerbF...
740263  suis  VERB  Mood=Ind|Number=Sing|Person=1|Tense=Pres|VerbF...
764653  suis  VERB  Mood=Ind|Number=Sing|Person=1|Tense=Pres|VerbF...

                                 sentence
3                       Je suis une femme
9                       Je suis un garçon
13                          Je suis riche
16                          Je suis rouge
158                     Je suis d' accord
...                                   ...
706231  Elle est jeune et je suis vieille
706249     Non monsieur je suis allemande
738926         Je suis dans le restaurant
740263                   Je suis contente
764653              Je suis au restaurant

[168 rows x 4 columns]

&emsp;b) Supplment Token Level Data
 * Specifically, I am using the Lexique data base to add information about syllable count, general word frequency to give allusion to how complex or uncommon the word is

In [6]:
lexique = pd.read_csv('data/OpenLexicon.tsv', sep='\t')
lexique = lexique.rename(columns={'ortho': 'token', 'Lexique4__Lemme' : 'lemma','Lexique4__SyllNb' : 'syllable_count'})
lexique.head(5)

,token,lemma,Lexique4__Cgram,Lexique4__CgramOrtho,Lexique4__FreqOrtho,syllable_count
0,a,a,NOM,"NOM,AUX,VER",11684.443,1
1,a,avoir,VER,"NOM,AUX,VER",11684.443,1
2,a,avoir,AUX,"NOM,AUX,VER",11684.443,1
3,a capella,a capella,ADV,ADV,0.244,4
4,a cappella,a cappella,ADV,ADV,0.241,4

 * The frequency column is how many times a word occurs out of a million instances. This is heavily skewed with a range of 11000+ to smaller that 0.3. For this reason I have decided to normalize the with column with a log transformation.

In [7]:
lexique['ortho_freq'] = np.log1p(lexique['Lexique4__FreqOrtho'])
tokens = pd.merge(
    tokens.assign(token_lower=tokens['token'].str.lower()),
    lexique[['token', 'syllable_count', 'ortho_freq']].rename(columns={'token': 'token_lower'}),
    on='token_lower',
    how='left'
).drop(columns='token_lower').drop_duplicates()

tokens.head(10)

,token,POS,Morpho-Syntactic_Features,sentence,syllable_count,ortho_freq
0,Le,DET,Definite=Def|Gender=Masc|Number=Sing|fPOS=DET++,Le garçon,1.0,9.713540
3,garçon,NOUN,Gender=Masc|Number=Sing|fPOS=NOUN++,Le garçon,2.0,5.244537
4,Je,PRON,Number=Sing|Person=1|PronType=Prs|fPOS=PRON++,Je suis une femme,1.0,10.163428
6,suis,VERB,Mood=Ind|Number=Sing|Person=1|Tense=Pres|VerbF...,Je suis une femme,1.0,8.330842
10,une,DET,Definite=Ind|Gender=Fem|Number=Sing|PronType=D...,Je suis une femme,1.0,9.039167
14,femme,NOUN,Gender=Fem|Number=Sing|fPOS=NOUN++,Je suis une femme,1.0,6.585643
15,La,DET,Definite=Def|Gender=Fem|Number=Sing|fPOS=DET++,La fille,1.0,9.613319
19,fille,NOUN,Gender=Fem|Number=Sing|fPOS=NOUN++,La fille,1.0,6.447431
20,Je,PRON,Number=Sing|Person=1|PronType=Prs|fPOS=PRON++,Je suis un garçon,1.0,10.163428
22,suis,VERB,Mood=Ind|Number=Sing|Person=1|Tense=Pres|VerbF...,Je suis un garçon,1.0,8.330842

 * There is a lot of interesting linguistic information that may have an effect on learner retention if we can **identify the lemma of the token**. Second language aquisition research suggests that learners of a language have a tendency to retain words that are congugates or closer relatives to one in their native tongue. This makes sense and I want to take advantage of this by engineering a feature column that describes the **edit distance** from the french word to english. As the lessons used in this data set are from an English based course I continue under the assumption users are more familiar with English and can use this knowledge to make inferences on French words. Although, I may consider reducing down to countries where this is particularly plausible (US, CA, etc.)

In [ ]:
tokenizer = MarianTokenizer.from_pretrained("Helsinki-NLP/opus-mt-fr-en")
model = MarianMTModel.from_pretrained("Helsinki-NLP/opus-mt-fr-en")

sentences = tokens['sentence'].unique().tolist()
fr_en_sentences = {}
for sentence in sentences:
    inputs = tokenizer(sentence, return_tensors="pt") # tokenize and convert to PyTorch tensors
    outputs = model.generate(**inputs) # "**" syntax unpacks inputs dict and output is tensor of english translation token ids
    translation = tokenizer.decode(outputs, skip_special_tokens=True)[0] # decode token ids to get english translation string
    fr_en_sentences[sentence] = translation

Loading weights: 100%|██████████| 256/256 [00:00<00:00, 17171.90it/s]

In [ ]:
fr_en_sentences

{'Le garçon': ['The boy'],
 'Je suis une femme': ["I'm a woman."],
 'La fille': ['The girl'],
 'Je suis un garçon': ["I'm a boy."],
 'Je suis riche': ["I'm rich."],
 'Je suis rouge': ["I'm red."],
 "L' homme": ['Man'],
 "L' homme est riche": ['The man is rich'],
 'Une pomme': ['Apple'],
 'Tu es un garçon': ["You're a boy."],
 'Je mange': ["I'm eating."],
 'Il est riche': ["He's rich."],
 'Elle est calme': ["She's calm."],
 'Il a un enfant': ['He has a child.'],
 'Il mange et je mange': ['He eats and I eat'],
 'La robe est rouge': ['The dress is red'],
 'Le chat est noir': ['The cat is black'],
 'Les hommes': ['Men'],
 'Nous sommes une femme et un homme': ['We are a woman and a man'],
 'Les hommes sont riches': ['Men are rich'],
 'Les hommes sont calmes': ['The men are calm.'],
 "J' écris": ["I'm writing."],
 "J' aime un garçon": ['I love a boy'],
 'Nous mangeons': ['We eat'],
 'Vous êtes calme': ["You're calm."],
 'Nous avons une pomme': ['We have an apple.'],
 'Le journal': ['The newspaper'],
 'Il lit un livre': ["He's reading a book."],
 'Nous lisons le menu': ['We read the menu'],
 'Les livres': ['Books'],
 'Ils sont riches': ["They're rich."],
 'Elles sont calmes': ["They're quiet."],
 'Les filles': ['Girls'],
 'Les femmes': ['Women'],
 'Les enfants': ['Children'],
 'Ils écrivent': ['They write'],
 'Ils mangent': ['They eat'],
 'Ils lisent': ['They read'],
 'Les filles et les garçons': ['Girls and boys'],
 'Ça va': ["It's okay."],
 'Oui merci': ['Yes, thank you.'],
 'Bonjour comment ça va': ["Hello, how's it going?"],
 'Non': ['No'],
 'Pardon': ['Excuse me.'],
 'Bonjour': ['Hello.'],
 'Merci au revoir': ['Thank you, good-bye.'],
 'Oui pardon': ["Yes, I'm sorry."],
 "S' il te plaît": ['Please.'],
 'Il y a un garçon': ["There's a boy."],
 'Ça va bien': ["It's okay."],
 'Comment vas - tu': ['How are you?'],
 "Je suis d' accord": ['I agree.'],
 'Bienvenue': ['Welcome'],
 'Merci et à bientôt': ['Thank you and see you soon.'],
 'Au revoir et à demain': ['Goodbye and tomorrow'],
 'Oui à plus tard': ["Yeah, I'll see you later."],
 'Désolé': ["I'm sorry."],
 'Non je suis désolé': ["No, I'm sorry."],
 'Bonne soirée': ['Good night.'],
 'Oui merci beaucoup': ['Yes, thank you very much.'],
 'Bonne nuit': ['Good night.'],
 'De rien': ["You're welcome."],
 'La soupe': ['Soup'],
 'La viande': ['Meat'],
 'Il a une fraise': ["He's got a strawberry."],
 'Je mange une baguette': ["I'm eating a baguette."],
 'Je mange une tomate': ['I eat a tomato'],
 'Elle mange de la viande': ['She eats meat.'],
 'Nous mangeons de la viande': ['We eat meat'],
 "L' eau": ['Water'],
 'Je bois et je mange': ['I drink and eat'],
 'Un œuf': ['An egg'],
 'Je mange une salade': ["I'm eating a salad."],
 'Un oignon': ['An onion'],
 "Je bois de l' eau": ['I drink water'],
 'Le vin': ['Wine'],
 'Le pain': ['Bread'],
 'Ils boivent': ['They drink'],
 'Je suis du Canada': ["I'm from Canada"],
 'La bière': ['Beer'],
 "Le lait et l' eau": ['Milk and water'],
 'Un repas': ['A meal'],
 "J' aime le thé": ['I like tea.'],
 "J' aime la crêpe": ['I like pancakes.'],
 'La boisson': ['Drinking'],
 'Nous mangeons du beurre': ['We eat butter'],
 'Le bonbon est rouge': ['The candy is red.'],
 "J' aime boire": ['I like to drink'],
 'Je mange une banane': ['I eat a banana'],
 'Le fromage et le pain': ['Cheese and bread'],
 "J' aime manger": ['I like to eat'],
 'Une carotte': ['A carrot'],
 'Sel et poivre': ['Salt and pepper'],
 'Nous mangeons du sucre': ['We eat sugar'],
 'Le gâteau est rouge et noir': ['The cake is red and black'],
 'Nous mangeons du poulet': ['We eat chicken'],
 'Les filles mangent avec les hommes': ['Girls eat with men'],
 'Je mange du porc': ['I eat pork'],
 'Le jus': ['Juice'],
 "L' huile": ['Oil'],
 'Un citron': ['A lemon'],
 'La confiture': ['Jam'],
 'Le raisin': ['Grapes'],
 "L' animal": ['Animal'],
 'Nous avons un chien': ["We've got a dog."],
 'Le cheval est un animal': ['Horse is an animal'],
 'Je suis un oiseau': ["I'm a bird."],
 'Un canard mange': ['A duck eats'],
 'Un cheval': ['A horse'],
 'Je suis un ours': ["I'm a bear."],
 'Il a un cochon': ["He's got a pig."],
 'La mouche': ['The fly'],
 'La vache mange': ['The cow eats'],
 'Je suis une tortue': ["I'm a turtle"],
 'Elle a un cochon': ["She's got a pig."],
 'Le tigre': ['The tiger'],
 'Je suis un serpent': ["I'm a snake."],
 'Le requin est rouge': ['The shark is red'],
 'Je suis un dauphin': ["I'm a dolphin."],
 'Le garçon a un singe': ['The boy has a monkey'],
 'Une abeille': ['A bee'],
 'Je suis une araignée': ["I'm a spider."],
 'Le loup et le chien': ['The wolf and the dog'],
 'Je suis un papillon': ["I'm a butterfly"],
 'Une baleine': ['A whale'],
 "Je mange l' insecte": ['I eat the insect'],
 'La fourmi mange une pomme': ['Ant eats an apple'],
 'Un insecte est un animal': ['An insect is an animal'],
 'La fourmi est un insecte': ['Ant is an insect'],
 'Un lapin est un animal': ['A rabbit is an animal'],
 'La poule aime la pomme': ['The chicken likes the apple'],
 'La poule et le canard': ['The chicken and the duck'],
 'Le vin est froid': ['The wine is cold'],
 'Je suis petit': ["I'm a kid."],
 'Non il est petit': ["No, he's small."],
 'Le pain est chaud': ['The bread is hot'],
 'La robe est nouvelle': ['The dress is new'],
 'La robe est noire': ['The dress is black'],
 'Le menu est nouveau': ['The menu is new'],
 'Elle est petite': ["She's small."],
 'Oui elle est jolie': ["Yeah, she's pretty."],
 'Je suis jeune': ["I'm young."],
 'Elle est grande': ["She's big."],
 'Je suis grand': ["I'm tall."],
 'La robe est chaude': ['The dress is hot'],
 'La soupe est froide': ['Soup is cold'],
 'Le gâteau est joli': ['The cake is pretty.'],
 'Les chiens': ['Dogs'],
 'Ils mangent des pommes': ['They eat apples.'],
 'Les éléphants mangent du pain': ['Elephants eat bread'],
 'Nous sommes petites': ["We're small."],
 'Les chats mangent du riz': ['Cats eat rice'],
 'Les chiens sont grands': ['Dogs are big'],
 'Les canards boivent': ['Ducks drink'],
 'Nous sommes seuls': ["We're alone."],
 'Ils écrivent des lettres': ['They write letters'],
 'Nous sommes grandes': ["We're big."],
 'Les jeunes femmes sont grandes': ['Young women are big'],
 'Un œuf et des fruits': ['An egg and fruit'],
 'Elle mange un citron et des fraises': ['She eats lemon and strawberries'],
 'Ils lisent seuls': ["They're reading alone."],
 'Le garçon mange des sandwichs': ['The boy eats sandwiches'],
 'Des poissons mangent du riz': ['Fish eat rice'],
 'Je mange des baguettes': ['I eat chopsticks'],
 'Les enfants mangent des légumes': ['Children eat vegetables'],
 'Les enfants mangent des haricots': ['Children eat beans'],
 'Ils mangent les frites': ['They eat the fries.'],
 'Ils mangent les crêpes': ['They eat pancakes'],
 'Nous mangeons des pâtes': ['We eat pasta'],
 "C' est un chien": ["It's a dog."],
 "J' ai du vin": ["I've got wine."],
 'Tu as des fraises': ["You've got strawberries."],
 'Ils ont du lait': ["They've got milk."],
 'Ce sont des pommes': ["They're apples."],
 'Tu me plais': ['I like you.'],
 'Voulez - vous danser avec moi': ['Do You Want to Dance With Me'],
 'Venez - vous ici souvent': ['Come Here Often'],
 'Tu es mannequin': ["You're a model."],
 'Voulez - vous sortir avec moi': ['Would you like to go out with me?'],
 'On va chez toi ou chez moi': ["We're going to your house or my house."],
 'Quel est ton nom': ["What's your name?"],
 "C' est le prince charmant": ["He's Prince Charming."],
 'Voulez - vous sortir avec moi un jour': ['Would you like to go out with me one day?'],
 'Je peux vous offrir un verre': ['I can buy you a drink.'],
 "Il fait chaud ici ou bien c' est toi": ["It's hot here or it's you."],
 'Salut beauté': ['Hello, beauty.'],
 'Il fait chaud ici ou est - ce juste toi': ["It's hot here or is it just you?"],
 'Le sac est rouge': ['The bag is red'],
 'Les vêtements': ['Clothing'],
 'Des chaussures': ['Shoes'],
 'Le costume': ['The costume'],
 'Les bottes': ['Boots'],
 'Les jupes': ['Skirts'],
 'Des chaussettes': ['Socks'],
 "L' écharpe": ['The scarf'],
 'Il a un gant noir': ["He's got a black glove."],
 'Le livre est noir': ['The book is black'],
 'Le riz est blanc': ['The rice is white'],
 'Le poisson est bleu': ['The fish is blue'],
 'Le serpent est violet': ['The snake is purple'],
 "L' éléphant est gris": ['The elephant is grey'],
 "L' ours est orange": ['The bear is orange'],
 'Ma robe': ['My dress'],
 'Sa robe est rouge': ['Her dress is red.'],
 'Ton éléphant': ['Your elephant'],
 'Leur chapeau est chaud': ["Their hat's hot."],
 'Votre chapeau': ['Your hat'],
 'Elle est avec ses enfants': ["She's with her kids."],
 'Mes robes': ['My dresses'],
 'Oui nous pouvons': ['Yes we can.'],
 'Elle adore ses enfants': ['She loves her children.'],
 "L' homme adore la femme": ['The man loves the woman'],
 'Comment': ['How'],
 'Lequel': ['Which one'],
 'Où': ['Where'],
 "J' aime laquelle": ['I like which one'],
 'Combien': ['How much'],
 'Lesquelles': ['Which'],
 'Quoi': ['What?'],
 'Qui': ['Who'],
 'Je porte un manteau': ["I'm wearing a coat."],
 'Je saisis mon chapeau': ["I'll get my hat."],
 'Elle propose du thé': ["She's offering tea."],
 'Il améliore son repas': ["He's improving his meal."],
 'Il est bête': ["He's stupid."],
 "C' est méchant": ["That's mean."],
 'Le garçon est drôle': ["The boy's funny."],
 "Je t' aime": ['I love you'],
 'On mange': ["We're eating."],
 "Elle t' aime": ['She loves you.'],
 "Oui je t' aime": ['Yes, I love you.'],
 "Elle l' aime": ['She loves him.'],
 'Le singe est gris': ['The monkey is gray'],
 "Ma femme je l' adore": ['My wife I love her.'],
 "Je l' ai": ["I've got it."],
 'Bonjour comment vas - tu': ['How are you?'],
 "Il t' aime": ['He loves you.'],
 'Il nous aime': ['He loves us.'],
 'Ils nous aiment': ['They love us.'],
 'Zéro': ['Zero'],
 "C' est leur mariage": ["It's their wedding."],
 'Mon neveu est beau': ['My nephew is beautiful.'],
 'Je mange cela': ["I'm eating this."],
 'Il mange cela': ['He eats this.'],
 'Comme ceci': ['Like this'],
 "Rien n' est éternel": ['Nothing is eternal'],
 'Ça va ça vient': ["It's all right."],
 'Même pas mal': ['Not even bad.'],
 'Sauve qui peut': ['Save who can'],
 'Il ne faut pas confondre vitesse et précipitation': ['Speed and precipitation should not be confused'],
 'Le monde appartient à ceux qui se lèvent tôt': ['The world belongs to those who rise early'],
 "Petit à petit l' oiseau fait son nid": ['Little by little the bird makes its nest'],
 'À Rome fais comme les Romains': ['In Rome do as the Romans do'],
 'Au secours': ['Help'],
 'Les murs ont des oreilles': ['The walls have ears'],
 'À chacun ses goûts': ['To each his tastes'],
 "On ne vit qu' une fois": ['You only live once.'],
 'Bonne journée': ['Have a good day.'],
 'La période': ['The period'],
 'On est jeudi': ["It's Thursday."],
 'En octobre': ['In October'],
 'De septembre à décembre': ['September to December'],
 'De juin à octobre': ['June to October'],
 'Demain à minuit': ['Tomorrow at midnight'],
 'Deux minutes et seize secondes': ['Two minutes and sixteen seconds'],
 'Il dure': ['It lasts'],
 'Difficile à dire': ["It's hard to say."],
 'Il peut venir': ['He can come.'],
 'Je vais lire': ["I'll read it."],
 'Il peut lire': ['He can read'],
 'Le petit déjeuner': ['Breakfast'],
 "J' aime vendre des légumes": ['I like to sell vegetables'],
 'Il aime marcher seul': ['He likes to walk alone.'],
 "J' aime griller la viande": ['I like to grill meat'],
 'Ma femme aime inviter sa famille': ['My wife likes to invite her family'],
 "J' aime griller du poulet": ['I like to grill chicken'],
 'Je suis là': ["I'm here."],
 'Merci bien': ['Thank you very much.'],
 "C' est très bon": ["It's very good."],
 'Mon chapeau est là': ["My hat's here."],
 'Le che f': ['Che f'],
 'Jamais': ['Never'],
 'Non jamais': ['No, never.'],
 'Nous non plus': ['Neither do we.'],
 "Personne n' aime cela": ['No one likes it.'],
 'Personne ne me parle': ["No one's talking to me."],
 'Personne ne veut cela': ['No one wants that.'],
 'Personne ne comprend pourquoi': ['No one understands why'],
 'Ni vous': ['Not you.'],
 'Ni le garçon ni la fille': ['Neither the boy nor the girl'],
 'Ni les fruits ni les légumes': ['Neither fruit nor vegetables'],
 'Je parle pendant que je mange': ['I talk while I eat'],
 "S' il parle nous parlons": ['If he talks, we talk.'],
 "D' accord si nous pouvons": ['Agree if we can'],
 'Je lis lentement': ["I'm reading slowly."],
 'Seulement je suis ici': ["Only I'm here."],
 'Peut - être': ['Perhaps'],
 "C' est presque rouge": ["It's almost red."],
 'Bon après - midi': ['Good afternoon'],
 'La table': ['The table'],
 'Le bol': ['The bowl'],
 'Il descend': ["He's coming down."],
 'Je suis dans la piscine': ["I'm in the pool."],
 'Où est ma serviette': ["Where's my towel?"],
 'Un outil': ['A tool'],
 'Il a une serviette': ["He's got a towel."],
 'Il ferme la porte': ["He's closing the door."],
 'Le savon est rose': ['Soap is pink'],
 'Les pièces': ['The pieces'],
 "L' arme": ['The weapon'],
 "L' objet": ['The object'],
 'Il allume quoi': ['What does it turn on?'],
 'Elle branche quoi': ["What's in it?"],
 'Il charge quoi': ["What's he charging?"],
 "C' est plat": ["It's flat."],
 "C' est réel": ["It's real."],
 'Je suis un homme libre': ["I'm a free man"],
 'Il est marié': ["He's married."],
 'Elle est là telle ma mère': ["She's like my mother."],
 "C' est terrible": ["It's terrible."],
 'Elle est blonde': ["She's blonde."],
 'Est - il franc': ['Is it frank?'],
 'Je suis franc': ["I'm honest."],
 'Il est franc': ["He's honest."],
 'Le vin est liquide': ['The wine is liquid'],
 'Sur quoi': ['On what'],
 'Il est avec nous ou contre nous': ["He's with us or against us."],
 'Je suis parmi vous': ["I'm with you"],
 'La route': ['The road'],
 'Le bord est rouge': ['The edge is red'],
 'La région est belle': ['The area is beautiful'],
 "C' est la côte": ["It's the coast."],
 'Le port': ['The port'],
 'La prison': ['Prison'],
 'Le bar': ['The bar'],
 'Le désert': ['The desert'],
 'Le pont': ['The bridge'],
 'Le pont est rouge': ['The bridge is red'],
 'Le zoo est grand': ['The zoo is big'],
 'Je visite': ["I'm visiting."],
 'Il visite': ["He's visiting."],
 'Couloir ou fenêtre': ['Corridor or window'],
 'Où est la discothèque': ["Where's the nightclub?"],
 'Nous sommes des animaux': ["We're animals."],
 'Il possède des animaux': ['He owns animals.'],
 'Les morceaux': ['Pieces'],
 'Elle a quinze bijoux': ["She's got fifteen jewels."],
 'Les chapeaux': ['Hats'],
 'Non madame': ["No, ma'am."],
 'Oui madame': ["Yes, ma'am."],
 "L' ennemie": ['The enemy'],
 'Mon père est un adulte': ["My father's an adult."],
 'Le citoyen': ['The citizen'],
 'Je suis un homme et un citoyen': ['I am a man and a citizen'],
 "J' aime ma petite amie": ['I love my girlfriend'],
 'Je parle français': ['I speak French'],
 "J' aime ma copine": ['I love my girlfriend'],
 'Un adolescent mange beaucoup': ['A teenager eats a lot'],
 'Il parle anglais': ['He speaks English'],
 'Il parle anglais et français': ['He speaks English and French'],
 'Le client est roi': ['The client is king'],
 'Il arrive': ["He's coming."],
 "Il l' affirme": ['He says so.'],
 'Elle vient après': ["She's coming after"],
 'Je vous demande': ["I'm asking you."],
 'Je crois': ['I think so.'],
 'Je pense': ['I think so.'],
 'Elle ment': ["She's lying."],
 'Oui je pense': ['Yes, I think so.'],
 'Elle part': ["She's leaving."],
 'Il plante des légumes': ["He's planting vegetables."],
 'Elle plante des légumes': ["She's planting vegetables."],
 'Il reçoit les clés': ['He gets the keys.'],
 'Il refuse': ['He refuses.'],
 'Il remarque une fille': ["He's noticing a girl."],
 'Il semble être riche': ['He seems to be rich.'],
 'Il réserve un livre': ["He's saving a book."],
 'Je vous ressemble': ['I look like you.'],
 'Je reste en Italie': ["I'm staying in Italy."],
 'Elle suppose cela': ['She supposes that.'],
 'Elle croyait sa mère': ['She believed her mother'],
 'Il croyait son père': ['He believed his father'],
 'Je ne pouvais pas dormir': ["I couldn't sleep."],
 'Oui il savait': ['Yes, he knew.'],
 'Je ne savais pas': ["I didn't know."],
 'Je suis né ici': ['I was born here.'],
 'Je suis née ici': ['I was born here.'],
 'Je suis née là': ['I was born there.'],
 'Elle a téléphoné à sa nièce': ['She called her niece.'],
 "J' ai passé trois heures ici": ['I spent three hours here.'],
 'Je suis allée au parc hier': ['I went to the park yesterday.'],
 'Je suis monté': ["I'm up."],
 'Il est mort': ["He's dead."],
 'Elle est morte': ["She's dead."],
 'Il a laissé deux enfants': ['He left two children.'],
 'Je me suis décidée': ['I made up my mind.'],
 'Elle a essayé': ['She tried.'],
 'Avez - vous parlé': ['Have You Talked?'],
 'Je me suis décidé': ['I made up my mind.'],
 'Sa mère a disparu': ["Her mother's gone."],
 'Elle a conduit comme ça': ['She drove like that.'],
 'Son père a disparu': ["Her father's gone."],
 'Elle a conduit sa voiture': ['She drove her car.'],
 'Nous avons réussi': ['We did it.'],
 'Il a réussi': ['He did it.'],
 'Il a permis cela': ['He allowed this to happen.'],
 'Oui il a su': ['Yeah, he knew.'],
 'Il a demandé à ma mère': ['He asked my mother.'],
 'Elle pourrait dormir': ['She could sleep.'],
 'Il a arrêté la voiture': ['He stopped the car.'],
 'Oui très récemment': ['Yes very recently'],
 "Elle n' a pas répondu": ["She didn't answer."],
 "J' ai répondu à sa lettre": ['I answered his letter.'],
 "Elle n' a jamais répondu": ['She never answered.'],
 'Tu as répondu': ['You answered.'],
 'La distance': ['Distance'],
 'La sortie est ici': ['The exit is here.'],
 'Le sud': ['The South'],
 'Quand est votre départ': ['When is your departure'],
 'Il a changé': ["He's changed."],
 "J' ai compris": ['I get it.'],
 'Elle a obtenu du vin': ['She got some wine.'],
 'Je suis rentrée très tard': ['I came home very late.'],
 'Avez - vous eu un chien': ['Have you had a dog?'],
 "J' ai eu assez": ["I've had enough."],
 'Il a tiré ma chemise': ['He pulled my shirt.'],
 'Nous avons commandé le repas': ['We ordered the meal'],
 'Tu as ajouté deux citrons': ['You added two lemons.'],
 'Il a envoyé deux lettres': ['He sent two letters.'],
 "J' ai attendu": ['I waited.'],
 "J' ai raté mon repas": ['I missed my meal.'],
 "J' ai raté mon dîner": ['I missed my dinner.'],
 'Trois moins deux égale un': ['Three minus two equals one'],
 'Quarante - sept ans': ['Forty - seven years'],
 'Un plus un égale deux': ['One plus one equals two'],
 'Dix trente cinquante cent': ['Ninety-five hundred'],
 'Qui veut un million': ['Who wants a million'],
 'Le chiffre': ['The number'],
 'Zéro est un chiffre': ['Zero is a number'],
 'Le chiffre est énorme': ['The number is huge'],
 'La peur': ['Fear'],
 'Mon amour': ['My love'],
 'Oui avec joie': ['Yes with joy'],
 'Un sentiment de bonheur': ['A feeling of happiness'],
 'Je suis triste': ["I'm sad."],
 'Vous avez beaucoup de courage': ['You have a lot of courage.'],
 'Je suis très heureux': ["I'm very happy."],
 'Merci pour votre patience': ['Thank you for your patience'],
 'Vous avez une bonne mémoire': ['You have a good memory.'],
 'Il est inquiet': ["He's worried."],
 'Je suis calme': ["I'm calm."],
 'Elle mange': ["She's eating."],
 'Un chat': ['A cat'],
 'Il est calme': ["He's calm."],
 'Nous aimons': ['We love'],
 'Elles écrivent': ['They write'],
 'Elles mangent': ['They eat'],
 'Merci': ['Thank you.'],
 'Oui': ['Yes'],
 'Salut': ['Hello.'],
 'Au revoir': ['Goodbye.'],
 "D' accord": ['Agreed.'],
 'Bonjour ça va': ["Hello, it's okay."],
 'Bonjour ça va bien': ["Hello, it's okay."],
 'Bonjour et bienvenue': ['Hello and welcome'],
 'Merci beaucoup': ['Thank you so much.'],
 'Bonsoir': ['Good evening.'],
 'Le riz': ['Rice'],
 'Elles boivent': ['They drink'],
 'La carotte': ['The carrot'],
 'Poivre': ['Pepper'],
 'Le sel': ['Salt'],
 'Le chat': ['The cat'],
 'Un chien mange': ['A dog eats'],
 'Je suis un lion': ["I'm a lion"],
 'Un dauphin': ['A dolphin'],
 'Un serpent': ['A snake'],
 'Un papillon': ['A butterfly'],